package hu.paninform.startmedsol.domain.enumeration;

/**
 * The AttendanceType enumeration.
 */
public enum AttendanceType {
    TYPE_1_FIRST_SPECIALIST_CARE, TYPE_2_RECALL, TYPE_3_MEDICAL_CONSULTATION, TYPE_4_FIRST_AID, TYPE_5_LONG_TERM_PATIENT_CONTROLL, TYPE_6_FILTRATION, TYPE_7_TAKING_CARE, TYPE_8_CARED_PAIENT, TYPE_9_DAY_CARE, TYPE_K_CARE_DUE_TO_INCAPACITY
}
