package hu.paninform.startmedsol.domain.enumeration;

/**
 * The InstitutionCategory enumeration.
 */
public enum InstitutionCategory {
    WITHOUT_LIMITATION, INPATIENT_MEDICAL_UNIT, OUTPATIENT_MEDICAL_UNIT, DESIGNATED_MEDICAL_UNIT, INPATIENT_AND_OUTPATIENT_BOTH, GP, SPEC_OF_DESIGN_MED_UNIT, DIABETES_TREATMENT_UNIT, MENOPAUSE_AND_OSTEOP_OUTPAT, OUTPAT_WITH_INPAT_BACKGROUND, CHILDREN_PSYCHO_OUTPAT_MED_UNIT
}
