export const enum MedicineType {
  MEDICINE = 'MEDICINE',

  IMMUN = 'IMMUN',

  INFANT_NUTRITION = 'INFANT_NUTRITION',

  RADIOPHARMACON = 'RADIOPHARMACON',

  HOMEOPATH = 'HOMEOPATH',

  BASE_MATERIAL = 'BASE_MATERIAL',

  FONO = 'FONO',

  WRAPPER = 'WRAPPER',

  MAKING_PRICE = 'MAKING_PRICE',

  MEDICAL_AID = 'MEDICAL_AID',
}
